networks:
  starlink:
    driver: bridge

services:
  web:
    command: [ "npm", "run", "start", "--", "--host", "0.0.0.0" ]
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - starlink
    build:
      context: .
      dockerfile: Dockerfile
      target: production
